image:
  file: .gitpod.Dockerfile

tasks:
  - name: Futurenet
    init: |
      docker pull stellar/quickstart:soroban-dev
    command: |
      docker run --rm -it \
      --name stellar \
      -p 8000:8000 \
      stellar/quickstart:soroban-dev \
      --futurenet \
      --enable-soroban-rpc
  # This "CLI - Futurenet" task opens a terminal for you to interact with the
  # futurenet network.
  - name: CLI - Testnet
    # We specify some required environment variables for use on the futurenet.
    env:
      # This can be set by the user, but this terminal is dedicated to futurenet so set for convenience.
      SOROBAN_RPC_URL: "https://soroban-testnet.stellar.org/"
      SOROBAN_NETWORK_PASSPHRASE: "Test SDF Network ; September 2015"
    # To keep things tidy, we clear the terminal from the previous output.
    command: |
      clear
  - name: CLI - Sandbox
    init: |
      chmod +x ./initialize.sh
    command: |
      curl -fsSL https://bun.sh/install | bash
      source /home/gitpod/.bashrc
      bun setup
      bun start
vscode:
  extensions:
    - rust-lang.rust-analyzer
    - vadimcn.vscode-lldb

ports:
  # Your quickstart node has a Horizon API server and an RPC endpoint, both
  # listening on port 8000. It's publicly accessible through the internet.
  - name: Futurenet
    port: 8000
    visibility: public
    onOpen: ignore
